// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdGUrwx6rhsp8vBgaqQ36MYA1vSsRCIyo',
    appId: '1:652239899684:web:50925471e4932e6a3d1cb1',
    messagingSenderId: '652239899684',
    projectId: 'fashion-closet-app',
    authDomain: 'fashion-closet-app.firebaseapp.com',
    storageBucket: 'fashion-closet-app.firebasestorage.app',
    measurementId: 'G-2HSBF1CR93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6QDtbwMZJBK_wDSq8yA2Vw90BgI7AMMY',
    appId: '1:652239899684:android:0dc2162ed6f28f943d1cb1',
    messagingSenderId: '652239899684',
    projectId: 'fashion-closet-app',
    storageBucket: 'fashion-closet-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMizr2quHIO4N_2_Dr5ZiyV6vskV5BKpI',
    appId: '1:652239899684:ios:e29c93ece6151f863d1cb1',
    messagingSenderId: '652239899684',
    projectId: 'fashion-closet-app',
    storageBucket: 'fashion-closet-app.firebasestorage.app',
    iosBundleId: 'com.example.fashionCloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMizr2quHIO4N_2_Dr5ZiyV6vskV5BKpI',
    appId: '1:652239899684:ios:e29c93ece6151f863d1cb1',
    messagingSenderId: '652239899684',
    projectId: 'fashion-closet-app',
    storageBucket: 'fashion-closet-app.firebasestorage.app',
    iosBundleId: 'com.example.fashionCloset',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdGUrwx6rhsp8vBgaqQ36MYA1vSsRCIyo',
    appId: '1:652239899684:web:1a3053f0da25acbf3d1cb1',
    messagingSenderId: '652239899684',
    projectId: 'fashion-closet-app',
    authDomain: 'fashion-closet-app.firebaseapp.com',
    storageBucket: 'fashion-closet-app.firebasestorage.app',
    measurementId: 'G-WC5FK63PCX',
  );
}